export default function() {
  return [
    {title: 'JavaScript: The Good Parts'},
    {title: 'Harry Potter'},
    {title: 'The Dark Tower'},
    {title: 'Eloquent Ruby'}
  ]
}

//Redux serves to conduct application state, React renders views. React-redux connects the two.
//our application state is generated by reducer functions. the books reducers always returns an array of BooksReducer
//array contains a list of objects; each object represents one books
//added books reducer to reducers call in index.js
