export default function() {
  return [
    {title: 'JavaScript: The Good Parts', pages: 33},
    {title: 'Harry Potter', pages: 53},
    {title: 'The Dark Tower', pages: 85},
    {title: 'Eloquent Ruby', pages: 100}
  ]
}

//Redux serves to conduct application state, React renders views. React-redux connects the two.
//our application state is generated by reducer functions. the books reducers always returns an array of BooksReducer
//array contains a list of objects; each object represents one books
//added books reducer to reducers call in index.js
